AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/**/*'
    - 'test/**/*'


Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 20