#production:
#  :SECRET_KEY_BASE: xxx
#  :DATABASE_URL: mysql://myname:mypass@localhost:3306/example_db
#  :ADMIN_USER_EMAIL: abc@gmail.com
#  :ADMIN_USER_PSWD: password
#  :NEW_RELIC_KEY: license_key
#  :ROLLBAR_ACCESS_TOKEN: rollbar_token
#  :CODECOV_TOKEN: CODECOV_TOKEN
#  :AWS_SMS_ACCESS_KEY_ID: access_key_id
#  :AWS_SMS_SECRET_ACCESS_KEY: secret_access_key
