#production:
#  :SECRET_KEY_BASE: xxx
#  :DATABASE_URL: mysql://myname:mypass@localhost:3306/example_db
#  :ADMIN_USER_EMAIL: abc@gmail.com
#  :ADMIN_USER_PSWD: password
#  :NEW_RELIC_KEY: license_key